### ISSUE TITLE
Pebble Time + iPhone 5s

### ISSUE THREAD

**Issue by aywengo** [tmszdmsk/pekkle#1]
Doesn't work with iPhone5s and Pebble Time Steel. User sees the empty screen.

**Comment by tmszdmsk** [comment]
Hi Roman,
thanks for letting me know. Now let's try to find out what's broken! ;)

My first guess is not clear enough affordance sent to you by first white screen (with tiny clock status bas on top) that is displayed when loading the list of stops (after the first call it's cached and works a little bit faster) and getting the phone's location. Could you tell me how long did you wait for stops to show up? 

Another thing is that error handling (to be honest - all the code) isn't the best right now so if any of the steps required to download the data failed - it will be hard to guess. I will work on that part from tomorrow. At least I know it's worth it! 

Thanks again!

**Comment by aywengo** [comment]
Thanks for your answer! I'd happy to help you. 
I was waiting quite a long - prob 5 minuts but without success.

**Comment by tmszdmsk** [comment]
5 minutes is way too long, it should take max 10 seconds. I will make more debugable release this week.

**Comment by tmszdmsk** [comment]
Hi again,

I just published the new version in the pebble market. Try it out ;)

**Comment by aywengo** [comment]
It is working now! Thank you very much!

**Comment by tmszdmsk** [comment]
Great!

If you have any comments and suggestions about the app - don't hesitate and write to me ;)
